### ISSUE TITLE
Help command not working

### ISSUE THREAD

**Issue by FlyingndCoding** [ZeroDiscord/EconomyBot#21]
The help command does not work:
![image](https://user-images.githubusercontent.com/94818620/145156554-dcee2d43-7df1-4fd9-9b71-8962690d7910.png)
![image](https://user-images.githubusercontent.com/94818620/145156608-7719dc7b-e336-435a-8912-738fbcb8eede.png)

**Comment by LegendaryEmoji** [comment]
You sure its working properly (script is running, no errors on starting or when you execute some command, bot is online)? Also `help` command needs embed permission.

**Comment by ZeroDiscord** [comment]
> You sure its working properly (script is running, no errors on starting or when you execute some command, bot is online)? Also `help` command needs embed permission.

^

**Comment by FlyingndCoding** [comment]
> You sure its working properly (script is running, no errors on starting or when you execute some command, bot is online)? Also `help` command needs embed permission.

Did n't notice the console but yea has embed perm

**Comment by ZeroDiscord** [comment]
> > You sure its working properly (script is running, no errors on starting or when you execute some command, bot is online)? Also `help` command needs embed permission.
> 
> Did n't notice the console but yea has embed perm

please do provide any console output whatsoever
