### ISSUE TITLE
error

### ISSUE THREAD

**Issue by SenexT1** [ZeroDiscord/EconomyBot#28]
C:\Users\mrmik\Desktop\EconomyBot-main\node_modules\discord.js\src\structures\Message.js:577
    if (typeof options !== 'object') return Promise.reject(new TypeError('INVALID_TYPE', 'options', 'object', true));
                                                           ^

TypeError [INVALID_TYPE]: Supplied options is not an object.
    at Message.delete (C:\Users\mrmik\Desktop\EconomyBot-main\node_modules\discord.js\src\structures\Message.js:577:60)
    at C:\Users\mrmik\Desktop\EconomyBot-main\counter.js:18:82
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  [Symbol(code)]: 'INVALID_TYPE'

**Comment by ZeroDiscord** [comment]
Make sure your message content intent is on
